spring.application.name=gestion_aulas


# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/gestion_aulas
spring.datasource.username=postgres
spring.datasource.password=crisan
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=MzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
jwt.expiration=86400000

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto de la aplicación
server.port=8080